### ISSUE TITLE
Show sum of all bids for one block

### ISSUE THREAD

**Issue by friedger** [mutharasus/MIA-Mining-Analysis#2]
It would be nice to list recent blocks with their total sum of commits, including those of mine-many.

**Comment by mutharasus** [comment]
@friedger  can you please look at the change I made to show which blocks the `mine-many` transactions apply to? If not may be I can create a different page that basically does a group by `block_height` to show the total STX mining a particular block. Only thing is it will show blocks that are not yet here. Perhaps that is what we need ?

**Comment by friedger** [comment]
While iterating through the tx the total per block_height could be collected (added for many block_height for mine-many) and the listed at the bottom of the page

**Comment by mutharasus** [comment]
Please check this chart I am working on in the `development` branch  (https://mia-mining-analysis-dev.mutharasus.repl.co/) 
to see if this covers what you are looking for. Still looking to validate and do some more testing. Will be adding this to the `prod` branch along with the table once ready. 

Just want to make sure this meets the expectations pertaining to this issue.
