### ISSUE TITLE
use api for contract address transactions

### ISSUE THREAD

**Issue by friedger** [mutharasus/MIA-Mining-Analysis#3]
Calling https://blockstack.github.io/stacks-blockchain-api/#operation/get_account_transactions returns recent txs of the contract.

**Comment by mutharasus** [comment]
Can you please elaborate. I am not following.

**Comment by friedger** [comment]
The api call returns all transactions related to the contract, nothing else.

Use something like
```
  requestify.get('https://stacks-node-api.stacks.co/extended/v1/address/SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-core-v1/transactions?limit=200')
```

**Comment by mutharasus** [comment]
This is a duplicate for issue #6
