### ISSUE TITLE
Why do you iterate over the tx in a block?

### ISSUE THREAD

**Issue by friedger** [mutharasus/MIA-Mining-Analysis#6]
It is enough to handle all contract calls of that one contract.

**Comment by mutharasus** [comment]
I dont follow.

Here is what I am doing (certainly a lot of room for improvement)

- I call this endpoint first to get the latest blocks: `https://stacks-node-api.stacks.co/extended/v1/block` which I am using to understand what the most recent confirmed block_height is.
- Then I am iterating over an array that starts at block 24497 and ends at the most recent block. This is a one time operation when the app starts up. For each block_height I am calling this end point to obtain the data `https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/block_height/{block_height}`
- I take the response JSON of each block and iterate over the transactions to parse out the data points necessary.
- I repeat this once every minute but for subsequent runs I ignore blocks that were previously processed so only running step 2 for the new blocks found. 

Please let me know what I can do to make this better.

**Comment by mutharasus** [comment]
It would be nice to not store the block by block data in memory but instead in a database such that I don't have to ever process the same block twice. Will add this as an improvement.

**Comment by mutharasus** [comment]
@friedger  I think I understand what you are saying. Essentially it would be easier to look at the transactions in the contract instead of fetching each block and looking for `mine-tokens` or `mine-many` transactions. Let me explore this and will let you know if I have any questions.

**Comment by mutharasus** [comment]
@friedger  So I am looking at the response JSON from calling `https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-core-v1/transactions?limit=50` which I would have to call iteratively with an `offset` to get transactions 50 at a time.  There is 1443 transactions in total right now.

The only trouble is I am thinking as I mentioned before I want to stand up a database and save the data so I don't have to keep refreshing the whole data every time the app has to restart.

I am not sure how I can know what I have already processed and saved and what I am yet to process and save.

Any thoughts on how I can accomplish this?

**Comment by friedger** [comment]
You get the tx in order. If you know the tx already just stop querying more.

You can use offset to get the next batch on boot up

**Comment by mutharasus** [comment]
Oh cool. That does sound like it might work better. Thanks.
