### ISSUE TITLE
Could a vertical line be added to indicate the current block?

### ISSUE THREAD

**Issue by cesalmo22** [mutharasus/MIA-Mining-Analysis#8]
Could a vertical line be added to indicate the current block?

![image0](https://user-images.githubusercontent.com/38565314/128581135-0fa8dcb0-cec8-4559-85bf-7732b0ac8c84.png)
#

**Comment by mutharasus** [comment]
Change deployed to dev: https://mia-mining-analysis-dev.mutharasus.repl.co Give it a whirl and let me know if it looks good and I will merge to Prod.
